framework:
    secret: '%env(APP_SECRET)%'
    session:
        handler_id: null # Si tu veux utiliser le gestionnaire de session par défaut
        save_path: '%kernel.cache_dir%/sessions' # L'endroit où les sessions seront sauvegardées
        cookie_secure: auto # Pour assurer que le cookie de session soit envoyé uniquement via HTTPS
        cookie_samesite: lax # Définit les politiques SameSite pour les cookies
